---
title: "Exploring the challenges"
date: today
date-format: iso
filters:
  - fontawesome
execute:
  error: true
bibliography: references.bib
format:
  html:
    toc: true
    code-fold: true
    df-print: paged
    theme:
      light: cerulean
      dark: darkly
    margin: 5% 0;
  pdf:
    keep-tex: true
    include-in-header:
      - text: |
          \usepackage{siunitx}
---

\newcommand{\ie}{*i.e.,*}
\renewcommand{\epsilon}{\varepsilon}

::: {.callout-important}
## Available on Gitlab
This note is available on [{{< fa brands gitlab title="Amaël's gitlab at IGN" >}}gitlab](https://gitlab.ign.fr/ale-squin/tarifs-emerge).
:::

## Introduction
In order to test my models, I first run dummy tests, with generated data. I build models slowly, from the simplest to the most complex. The first challenge is related to the model used by Christine Deleuze *et al*. (scripts given on 11 October 2024):
```r
#| eval: false
Modele_mai2 <- nlme(formTotNew ~ a + b*hdn + d*hsurd, data = Grdata.PV,
	start = c(a = 0.4, 0, b = 1.5, 0, d = 0.0005, 0),
	fixed = list(a + b + d ~ feuil.res), random = a + d ~ 1|nomessence2)
```
Few things raised a flag in my mind:

1. The R package `nlme`, non-linear mixed effect, is for repeated measured data and is based on @Lindstrom1990. Here, the repetition occurs within the species level, so I am not sure this package is the best adapted... I feel that `lme4` would have been better
2. `hdn` is the hardiness $\sqrt{c}/h$ while `hsurd` is what I call the 'slenderness', $h/c$. Therefore, there is a high (negative) correlation between these two explanatory variables!

The model `Modele_mai2` should be understood as follow:

