---
title: "Check intuitions on the parameters (once fitted)"
date: today
author: Amaël Le Squin
date-format: iso
filters:
  - fontawesome
  - siunitx-quarto
  - imagify
imagify:
  header-includes: |
    \usepackage{pgfplots}
    \pgfplotsset{compat=1.18}
    \usepgfplotslibrary{fillbetween}
    \usetikzlibrary{positioning}
    \usetikzlibrary{calc}
  pdf-engine: lualatex
pdf-engine: lualatex
keep-tex: true
execute:
  error: true
  echo: false
  warning: false
  message: false
bibliography: /home/ALe-Squin/work/library/bib_file/references.bib
lightbox:
  match: auto
css: style.css
knitr:
  opts_chunk: 
    dev: ragg_png
    crop: null
    out.width: "70%"
    fig.width: 6
    fig.asp: 0.618
    fig.align: "center"
format:
  html:
    toc: true
    include-in-header: mathjax.html
    code-fold: true
    df-print: paged
    number-sections: true
    theme:
      light: cerulean
      dark: darkly
    margin: 5% 0;
  pdf:
    mathspec: true
    include-in-header:
      - text: |
          \usepackage{unicode-math}
---

<!-- New command -->
\newcommand{\ie}{*i.e.,*}

<!-- Math commands -->
\newcommand{\Vbft}{V_{\text{BFT}}}
\newcommand{\Fbft}{F_{\text{BFT}}}
\newcommand{\Vtot}{V_{\text{tot}}}
\newcommand{\Vzh}{V_{\text{Zhou}}}
\newcommand{\hdec}{h_{\text{dec}}}
\newcommand{\fmax}{f_{\text{max}}}

<!-- Math operators -->
<!-- \DeclareMathOperator{\ln}{ln} -->

<!-- -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= -->
<!-- ---------------------------   LOADING DATA, R CODE   --------------------------- -->
<!-- -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= -->

```{r}
#| output: false

#### Clear space and load packages
rm(list = ls())
graphics.off()

options(max.print = 500)

library(data.table)
library(cmdstanr)

source("./toolFunctions.R")
```

<!-- -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= -->
<!-- ---------------------------   MAIN CONTENT, R CODE   --------------------------- -->
<!-- -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= -->

```{r}
#### Plot different parts of the function
## Functions
r_func = function(x, pars)
{
	return ((pars["m"] - pars["c"]) * exp(pars["j"] - pars["k"]*x) * (pars["k"]*x/pars["j"])^pars["j"] +
		pars["c"] - (pars["c"] - pars["n"])*exp(-pars["s"]*x));
}

r_func_approx = function(x)
{
	return ((0.84 - 0.74) * exp(0.7 - 1.49*x) * (1.49*x/0.7)^0.7 +
		0.74 - (0.74 - 0.11)*exp(-44.17*x));
}

r_func_1 = function(x, pars)
{
	return ((pars["m"] - pars["c"]) * exp(pars["j"] - pars["k"]*x) * (pars["k"]*x/pars["j"])^pars["j"]);
}

r_func_2 = function(x, pars)
{
	return (pars["c"] - (pars["c"] - pars["n"])*exp(-pars["s"]*x));
}

## Extract parameters
fagsyl = readRDS("./yang/Fagus-sylvatica.rds")
pars = getParams(model_cmdstan = fagsyl, params_names = c("m", "c", "j", "k", "n", "s"))
rm(fagsyl)

round(pars, 2)

pars["s"]*pars["j"]/pars["k"]

## Plot
curve(r_func(x, pars), axes = FALSE, xlab = "Bole volume", ylab = "f(x)", lwd = 3, to = 4.5, ylim = c(0, 0.9))
curve(r_func_1(x, pars), add = TRUE, lwd = 3, col = "#FAB255")
curve(r_func_2(x, pars), add = TRUE, lwd = 3, lty = "dashed", col = "#0F7BA2")
curve(r_func_approx(x), add = TRUE, lwd = 3, lty = "dashed", col = "#CD212A")
axis(1)
axis(2, las = 1)
legend("topright", legend = c("Transition", "Juvenile"), fill = c("#FAB255", "#0F7BA2"))
```

```{r}
## Extract parameters
lardec = readRDS("./yang/Larix-decidua_submodel.rds")
pars = getParams(model_cmdstan = lardec, params_names = c("alpha", "beta_", "gamma", "delta"))
pars_equivalent = c(m = unname(pars["gamma"])/unname(pars["beta_"])*exp(-1) + unname(pars["alpha"]),
	c = unname(pars["alpha"]),
	j = 1,
	k = unname(pars["beta_"]),
	n = unname(pars["alpha"]) + unname(pars["delta"]),
	s = unname(pars["beta_"]))
rm(lardec)

round(pars, 2)

## Plot
curve(r_func(x, pars_equivalent), axes = FALSE, xlab = "Bole volume", ylab = "f(x)",
	lwd = 3, to = 3, ylim = c(0, 0.9))
curve(r_func_1(x, pars_equivalent), add = TRUE, lwd = 3, col = "#FAB255", to = 3)
curve(r_func_2(x, pars_equivalent), add = TRUE, lwd = 3, lty = "dashed", col = "#0F7BA2")
axis(1)
axis(2, las = 1)
legend("topright", legend = c("Transition", "Juvenile"), fill = c("#FAB255", "#0F7BA2"))
```