---
title: "Get informations on the French data"
date: today
author: Amaël Le Squin
date-format: iso
filters:
  - fontawesome
  - siunitx-quarto
  - imagify
imagify:
  header-includes: |
    \usepackage{pgfplots}
    \pgfplotsset{compat=1.18}
    \usepgfplotslibrary{fillbetween}
    \usetikzlibrary{positioning}
    \usetikzlibrary{calc}
  pdf-engine: lualatex
pdf-engine: lualatex
keep-tex: true
execute:
  error: true
  echo: false
  warning: false
  message: false
bibliography: /home/ALe-Squin/work/library/bib_file/references.bib
lightbox:
  match: auto
css: style.css
knitr:
  opts_chunk: 
    dev: ragg_png
    crop: null
    out.width: "70%"
    fig.width: 6
    fig.asp: 0.618
    fig.align: "center"
format:
  html:
    toc: true
    include-in-header: mathjax.html
    code-fold: true
    df-print: paged
    number-sections: true
    theme:
      light: cerulean
      dark: darkly
    margin: 5% 0;
  pdf:
    mathspec: true
    include-in-header:
      - text: |
          \usepackage{unicode-math}
---

<!-- New command -->
\newcommand{\ie}{*i.e.,*}

<!-- Math commands -->
\newcommand{\Vbft}{V_{\text{BFT}}}
\newcommand{\Fbft}{F_{\text{BFT}}}
\newcommand{\Vtot}{V_{\text{tot}}}
\newcommand{\Vzh}{V_{\text{Zhou}}}
\newcommand{\hdec}{h_{\text{dec}}}
\newcommand{\fmax}{f_{\text{max}}}

<!-- Math operators -->
<!-- \DeclareMathOperator{\ln}{ln} -->

<!-- -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= -->
<!-- ---------------------------   LOADING DATA, R CODE   --------------------------- -->
<!-- -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= -->

```{r}
#| output: false

#### Clear space and load packages
rm(list = ls())
graphics.off()

options(max.print = 500)

library(data.table)
library(cmdstanr)
	register_knitr_engine(override = TRUE)
library(stringi)
library(inventR)
library(gt)
```

```{r}
#### Loading data
## French NFI data query
db = connect_db()

vol_dt = ocre_nm(ans = 2021:2025, vars = c("V", "V0"), vent_a = "ess:ESS")

disconnect_db(db)

## Path
os = Sys.info()[['sysname']]
mnt_point = "/mnt/local_share/"
if (os == "Linux" || os == "Darwin")
{
	if (!dir.exists(mnt_point))
		stop(paste0("The mounting point <", mnt_point, "> does not exist"))
} else if (os == "Windows") {
	stop("TO DO!!! No idea how that works on Windows!")
} else {
	stop(paste("Unknown Operating System:", os))
}

path_data = paste0(mnt_point, "data/")
if (!dir.exists(path_data))
	stop(paste0("Folder <", path_data, "> does not exist! Did you run 01_prepare_data.qmd?"))

## Loading training dataset
training_dt_sp_specific = readRDS(paste0(path_data, "data_Vtot.rds"))
training_dt = readRDS(paste0(path_data, "data_Vtot-group.rds"))

## Get species name (sci) from NFI codes
nfi_codes = readRDS(paste0(path_data, "species_dt.rds"))[!is.na(species_code_nfi),
	.(speciesName_sci, species_code_nfi)]
setkey(nfi_codes, speciesName_sci)

# lala = copy(vol_dt)
# vol_dt = copy(lala)
```

<!-- -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= -->
<!-- ---------------------------   MAIN CONTENT, R CODE   --------------------------- -->
<!-- -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= -->

```{r}
#### Cleaning the data
## Keep column of interest and rename
vol_dt = vol_dt[, .(sp_code = ess.ess, vars, total = tot)]
vol_dt = vol_dt[(sp_code != "")]

## List species code that do not have a scientific name
missing_sp = vol_dt[which(!(sp_code %in% nfi_codes[, species_code_nfi])), unique(sp_code)]
missing_vol = vol_dt[sp_code %in% missing_sp, .(total = sum(total)), by = .(vars)]

## Sum sp-specific total volumes and bole volumes (before merge, so even missing sp are included)
vbole_sum = vol_dt[vars == "V", sum(total)]
vtot_sum = vol_dt[vars == "V0", sum(total)]

## Merge data
vol_dt = merge.data.table(vol_dt, nfi_codes, by.x = "sp_code", by.y = "species_code_nfi")
```

```{r}
#### Compute sp-specific percentage of volumes in French forest
percent_bole = vol_dt[vars == "V", .(percent = total/vbole_sum*100), by = speciesName_sci]
percent_tot = vol_dt[vars == "V0", .(percent = total/vtot_sum*100), by = speciesName_sci]

setkey(percent_bole, speciesName_sci)
setkey(percent_tot, speciesName_sci)

ls_trained_sp = training_dt_sp_specific[, unique(speciesName_sci)]

percent_bole[ls_trained_sp, sum(percent, na.rm = TRUE)]
percent_tot[ls_trained_sp, sum(percent, na.rm = TRUE)]
```

## Predict on Henri's data

### Assigning corresponding model to each espar

```{r}
#### Prepare data
## Loading
henri_dt = fread("../data/data_IFN_volume_2020_2024.csv")

## Prepare species groups
# Load data
sp_sci = readRDS("../../gohon_florence/species.rds")[, .(tarif, speciesName_sci)]
sp_code = readRDS("../../gohon_florence/espar.rds")[, .(espar, ess, Group_ess)]

# Merging
sp_code = merge.data.table(sp_code, sp_sci, by.x = "ess", by.y = "tarif", all.x = TRUE)
setkey(sp_code, espar)

# Change ess to char in Henri's data + leading zeros
# henri_dt[, ess := sprintf("%02d", ess)]

ls_espar = sort(henri_dt[, unique(espar)])

all(ls_espar %in% sp_code[, espar])

# Subset to listed ess
sp_code = sp_code[.(ls_espar)]

## Now, assign a model. It will be either the species, the group, or broadleaf/conifer
sp_specific_models = readRDS("./yang/rsquared_flopp_yang.rds")[, .(species, model = selected)]

aa = merge.data.table(sp_code, sp_specific_models,
	by.x = "speciesName_sci", by.y = "species", all.x = TRUE)

aa[model == "yang",
	model := paste0("./yang/", stri_replace(speciesName_sci, regex = " ", replacement = "-"), "_new.rds")]

aa[model == "sub",
	model := paste0("./yang/", stri_replace(speciesName_sci, regex = " ", replacement = "-"), "_submodel.rds")]

ls_models = readRDS("./yang/group-success.rds")

ls_full_gr = ls_models[(success_full), group]
aa[is.na(model) & Group_ess %in% ls_full_gr, model := paste0("./yang/", Group_ess, ".rds")]

ls_sub_gr = ls_models[(success_sub), group]
aa[is.na(model) & Group_ess %in% ls_sub_gr, model := paste0("./yang/", Group_ess, "_submodel.rds")]

## Assign generic models for groups that were not parametrised (A2), and for groups with too little indiv
ls_pb = c(aa[(is.na(model)), unique(Group_ess)], ls_models[N_indiv < 100, group])
aa[(Group_ess %in% ls_pb) & ess < 50, model := "./yang/broadleaf_new.rds"]
aa[(Group_ess %in% ls_pb) & ess > 50, model := "./yang/conifer_new.rds"]

## Merge the model listing with henri's dataset
henri_dt = merge.data.table(henri_dt, aa[, .(espar, model)], by = "espar")

training_dt[, .N, by = group][order(group)]
setkey(training_dt, speciesName_sci)
```

### Predicting total volume on Henri's data
```{r}
ls_filenames = henri_dt[, unique(model)]
ls_species = stri_replace(sp_specific_models[species != "Quercus sp.", species], regex = " ", replacement = "-")
ls_groups = ls_models[, group]

setkey(henri_dt, model)

henri_dt[, u_v0_modif := u_v0]
henri_dt[u_v0 < v, u_v0_modif := 1.01*v] # Must do that otherwise genQ will bug...

henri_dt[, vtot_pred := NA_real_]

broadleaves = c("Fagus sylvatica", "Fraxinus excelsior", "Quercus petraea", "Quercus sp.")
conifers = training_dt_sp_specific[, unique(speciesName_sci)]
conifers = conifers[!(conifers %in% broadleaves)]

for (fitname in ls_filenames)
{
	print(paste("Running", fitname))
	
	## Check if it is a fitted species or a fitted group
	is_species = FALSE
	is_group = FALSE
	is_conifer = FALSE
	is_broadleaf = FALSE
	if (any(stri_detect(str = fitname, regex = ls_species)))
	{
		is_species = TRUE
		current_sp = ls_species[stri_detect(str = fitname, regex = ls_species)]
		current_sp = stri_replace(str = current_sp, regex = "-", replacement = " ")
	} else if (any(stri_detect(str = fitname, regex = ls_groups))) {
		current_gr = ls_groups[stri_detect(str = fitname, regex = ls_groups)]
		is_group = TRUE
	} else {
		if (stri_detect(str = fitname, regex = "conifer_new"))
			is_conifer = TRUE
		if (stri_detect(str = fitname, regex = "broadleaf_new"))
			is_broadleaf = TRUE
	}
	
	## Check if it is simplified or not
	is_simplif = FALSE # Full model by default, ending by $group.rds or $species_new.rds
	if (stri_detect(str = fitname, regex = "_submodel.rds"))
		is_simplif = TRUE
	
	## Compile model
	genQ = cmdstan_model("./yang2024-genQ.stan")
	if (is_simplif)
		genQ = cmdstan_model("./yang2024-genQ_submodel.stan")

	## Create stan data
	if (is_species)
	{
		stanData_gen = list(
			N = training_dt[current_sp, .N],
			bole_volume_m3 = training_dt[current_sp, bole_volume_m3],
			total_volume_m3 = training_dt[current_sp, total_volume_m3],
			N_new = henri_dt[fitname, .N],
			bole_volume_m3_new = henri_dt[fitname, v],
			total_volume_m3_new = henri_dt[fitname, u_v0_modif]
		)
	} else if (is_group) {
		if (training_dt[group == current_gr, .N] == 0)
			next

		stanData_gen = list(
			N = training_dt[group == current_gr, .N],
			bole_volume_m3 = training_dt[group == current_gr, bole_volume_m3],
			total_volume_m3 = training_dt[group == current_gr, total_volume_m3],
			N_new = henri_dt[fitname, .N],
			bole_volume_m3_new = henri_dt[fitname, v],
			total_volume_m3_new = henri_dt[fitname, u_v0_modif]
		)
	} else if (is_conifer) {
		stanData_gen = list(
			N = training_dt[.(conifers)][, .N],
			bole_volume_m3 = training_dt[.(conifers)][, bole_volume_m3],
			total_volume_m3 = training_dt[.(conifers)][, total_volume_m3],
			N_new = henri_dt[fitname, .N],
			bole_volume_m3_new = henri_dt[fitname, v],
			total_volume_m3_new = henri_dt[fitname, u_v0_modif]
		)
	} else if (is_broadleaf) {
		stanData_gen = list(
			N = training_dt[.(broadleaves)][, .N],
			bole_volume_m3 = training_dt[.(broadleaves)][, bole_volume_m3],
			total_volume_m3 = training_dt[.(broadleaves)][, total_volume_m3],
			N_new = henri_dt[fitname, .N],
			bole_volume_m3_new = henri_dt[fitname, v],
			total_volume_m3_new = henri_dt[fitname, u_v0_modif]
		)
	} else {
		stop("stanData_gen not created: there is no matching case...")
	}
	
	## Generate predictions on Henri's data
	fit = readRDS(fitname)
	n_chains = fit$num_chains()
	n_iter = fit$metadata()$iter_sampling

	sim = genQ$generate_quantities(fit, data = stanData_gen,
		seed = 1969 - 08 - 18, parallel_chains = min(n_chains, 4))

	predGen = apply(X = sim$draws("v_gen_mean"), MARGIN = 3, FUN = mean)
	henri_dt[fitname, vtot_pred := predGen]
	rm(sim, fit, stanData_gen)

	## Remove temporary file as it saturates the memory otherwise...
	tmp = tempdir()
	ls_files = list.files(tmp)
	ls_files = ls_files[stri_detect(ls_files, regex = "^yang2024-genQ.*.csv$")]
	file.remove(paste0(tmp, "/", ls_files))
}

saveRDS(henri_dt[, .(npp, a, v, u_v0, vtot_pred)], "./u_v0_tarif_amael.rds")
```
