---
title: "Notes sur les copulas"
date: today
author: Amaël Le Squin
date-format: iso
filters:
  - fontawesome
  - siunitx-quarto
  - imagify
imagify:
  header-includes: |
    \usepackage{pgfplots}
    \pgfplotsset{compat=1.18}
    \usepgfplotslibrary{fillbetween}
    \usetikzlibrary{positioning}
    \usetikzlibrary{calc}
  pdf-engine: lualatex
pdf-engine: lualatex
keep-tex: true
execute:
  error: true
  echo: false
  warning: false
  message: false
bibliography: ./centralised_bibliography/references.bib
lightbox:
  match: auto
css: style.css
knitr:
  opts_chunk: 
    dev: ragg_png
    crop: null
    out.width: "70%"
    fig.width: 6
    fig.asp: 0.618
    fig.align: "center"
format:
  html:
    toc: true
    include-in-header: mathjax.html
    code-fold: true
    df-print: paged
    number-sections: true
    theme:
      light: cerulean
      dark: darkly
    margin: 5% 0;
  pdf:
    mathspec: true
    include-in-header:
      - text: |
          \usepackage{unicode-math}
---

```{r}
library(data.table)
# library(copula)
```

## Introduction

Notes résumant et explorant d'abord @Genest2007 puis [un post sur les copulas](https://bggj.is/posts/stan-copulas-1/index.html), et que j'adapte ici à deux variables gammamiquement distribuées (genre ce qui m'intéresse pour les volumes!).

## Lecture de @Genest2007

### Données
Le jeu de données est constitué de six mesure (voir @fig-data).
```{r}
data = data.table(i = 1:6, X = c(-2.224, -1.538, -0.807, 0.024, 0.052, 1.324),
	Y = c(0.431, 1.035, 0.586, 1.465, 1.115, -0.847))
```

```{r}
#| fig-cap: Jeu de données
#| label: fig-data

plot(data$X, data$Y, pch = 19, axes = FALSE, xlab = "X", ylab = "Y")
axis(1)
axis(2, las = 1)
```

### Dependence and ranks
